{% set name = "diive" %}
{% set version = "0.76.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/holukas/diive/archive/v{{ version }}.tar.gz
  sha256: 588c07c3bbf459f969e51406822e28628098dcfbba995d4a0822604f8dff3eec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<3.12
    - pandas >=2.1.0
    - scipy >=1.11.2
    - scikit-learn >=1.3.0
    - matplotlib-base >=3.7.3
    - pyyaml >=6.0.1
    - uncertainties >=3.1.7
    - statsmodels >=0.14.0
    - prophet >=1.1.4
    - seaborn >=0.12.2
    - bokeh >=3.2.2
    - pyarrow >13.0.0
    - pymannkendall >=1.4.3
    - yellowbrick >=1.5.0
    - shap >=0.42.1
    - eli5 >=0.13.0
    - xgboost >=2.0.0

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/holukas/diive
  summary: 'Time series processing library'

extra:
  recipe-maintainers:
    - inkenbrandt
